site_name: EDev Shell Tool
site_url: https://enthdev.github.io/edevshelltool/
site_description: A cross platform shell script tool.
site_author: Enthusiastic Development

repo_url: https://github.com/EnthDev/edevshelltool/

pages:
- Home: index.md
- User Guide:
    - Configuration: user-guide/configuration.md
- About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

extra_css:
- css/extra.css

markdown_extensions:
    - toc:
        title: "Table of Contents"
        permalink: "#"
        separator: "-"
    - admonition:

copyright: Maintained by the <a href="https://github.com/EnthDev">Enthusiastic Development</a> Team.
google_analytics: ['UA-93782605-1', 'enthdev.github.io/edevshelltool']
